# The script loops through the folders and generate a dataframe (table) with:
* All HEI names
* Number of accounts at each HEI at different time point

In [1]:
# import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# calculate pct change of the uni growth

def uni_growth(series_new, series_og):
    pct = np.absolute(series_new - series_og) / series_og
    pct = round(pct, 2)
    return pct

## Drupal merge

In [53]:
# import january 26
path_janD = 'C:/Users/ywa/Documents/Data/UserReport/Jan_2026_Moodle/hei_data_drupal.xlsx'

jan26_D = pd.read_excel(path_janD)


# import december 25
path_decD = 'C:/Users/ywa/Documents/Data/UserReport/Dec_2025_Moodle/hei_data_drupal.xlsx'

dec25_D = pd.read_excel(path_decD, usecols = ['count', 'provider'])

# merge jan26 and dec25

merged_drupal = jan26_D.merge(dec25_D, how = 'left', on = 'provider', validate = 'one_to_one')

merged_drupal.columns = ['provider', 'Jan_2026', 'state', 'Dec_2025']

# import september 25

path_sepD = 'C:/Users/ywa/Documents/Data/UserReport/Sep_2025_Moodle/hei_data_drupal.xlsx'

sep_25_D = pd.read_excel(path_sepD, usecols = ['count', 'provider'])

merged_drupal = merged_drupal.merge(sep_25_D, how = 'left', on = 'provider', validate = 'one_to_one')

merged_drupal.columns = ['provider', 'Jan_2026', 'state', 'Dec_2025', 'Sep_2025']

merged_drupal.head()

# import july 25

path_julD = 'C:/Users/ywa/Documents/Data/UserReport/Jul_2025_Moodle/hei_data_drupal.xlsx'

jul_25_D = pd.read_excel(path_julD, usecols = ['count', 'provider'])

merged_drupal = merged_drupal.merge(jul_25_D, how = 'left', on = 'provider', validate = 'one_to_one')

merged_drupal.columns = ['provider', 'Jan_2026', 'state', 'Dec_2025', 'Sep_2025', 'Jul_2025']

merged_drupal.head()

# import april 25

path_aprD = 'C:/Users/ywa/Documents/Data/UserReport/Apr_2025_Moodle/hei_data_drupal.xlsx'

apr_25_D = pd.read_excel(path_aprD, usecols = ['count', 'provider'])

merged_drupal = merged_drupal.merge(apr_25_D, how = 'left', on = 'provider', validate = 'one_to_one')

merged_drupal.columns = ['provider', 'Jan_2026', 'state', 'Dec_2025', 'Sep_2025', 'Jul_2025', 'Apr_2025']

# reordering columns

merged_drupal = merged_drupal.iloc[:, [0, 2, 1, 3, 4, 5, 6]]

merged_drupal.head()

,provider,state,Jan_2026,Dec_2025,Sep_2025,Jul_2025,Apr_2025
0,TH Nürnberg Georg Simon Ohm,Bayern,5609,37.0,32.0,32.0,27.0
1,HHU Düsseldorf,Nordrhein-Westfalen,2058,1935.0,1730.0,1600.0,1442.0
2,TH Köln,Nordrhein-Westfalen,1378,1361.0,1238.0,1185.0,1112.0
3,DHBW,Baden-Württemberg,686,667.0,618.0,586.0,427.0
4,Universität Bonn,Nordrhein-Westfalen,686,477.0,257.0,234.0,217.0

In [46]:
# deal with missing values (due to merge)
merged_drupal.fillna(0, inplace = True)

In [48]:


merged_drupal['rate_JanDec2526'] = uni_growth(merged_drupal['Jan_2026'], merged_drupal['Dec_2025'])
merged_drupal['rate_DecSep25'] = uni_growth(merged_drupal['Dec_2025'], merged_drupal['Sep_2025'])
merged_drupal['rate_SepJul25'] = uni_growth(merged_drupal['Sep_2025'], merged_drupal['Jul_2025'])
merged_drupal['rate_JulApr25'] = uni_growth(merged_drupal['Jul_2025'], merged_drupal['Apr_2025'])

#merged_drupal.head()

#merged_drupal = merged_drupal.iloc[:, [0, 1, 2, 7, 3, 8, 4, 9, 5, 10, 6]]

merged_drupal.head(10)

,provider,state,Jan_2026,rate_JanDec2526,Dec_2025,rate_DecSep25,Sep_2025,rate_SepJul25,Jul_2025,rate_JulApr25,Apr_2025
0,TH Nürnberg Georg Simon Ohm,Bayern,5609,150.59,37.0,0.16,32.0,0.00,32.0,0.19,27.0
1,HHU Düsseldorf,Nordrhein-Westfalen,2058,0.06,1935.0,0.12,1730.0,0.08,1600.0,0.11,1442.0
2,TH Köln,Nordrhein-Westfalen,1378,0.01,1361.0,0.10,1238.0,0.04,1185.0,0.07,1112.0
3,DHBW,Baden-Württemberg,686,0.03,667.0,0.08,618.0,0.05,586.0,0.37,427.0
4,Universität Bonn,Nordrhein-Westfalen,686,0.44,477.0,0.86,257.0,0.10,234.0,0.08,217.0
5,Charité - Universitätsmedizin Berlin,Berlin,680,0.08,629.0,0.15,545.0,0.16,468.0,0.30,360.0
6,Hochschule Meißen (FH) und Fortbildungszentrum,Sachsen,668,0.00,668.0,0.00,669.0,0.00,668.0,0.01,662.0
7,Universität Wuppertal,Nordrhein-Westfalen,639,1.53,253.0,0.26,200.0,0.43,140.0,0.36,103.0
8,Instanbul Technical University,Not in Germany,577,0.02,567.0,inf,0.0,NaN,0.0,NaN,0.0
9,Universität Duisburg-Essen,Nordrhein-Westfalen,550,0.09,503.0,0.20,418.0,0.13,371.0,0.17,316.0

In [49]:
# export excel to to drive
#merged_drupal.to_excel('C:/Users/ywa/Documents/Data/UserReport/HEI_semester_growth_D.xlsx', index = False)

## Moodle merge

In [14]:
# import the existing table
existing_path_M = 'C:/Users/ywa/Documents/Data/UserReport/HEI_semester_growth_M.xlsx'

existing_df_M = pd.read_excel(existing_path)

existing_df_M.head()

,provider,state,Jan_2026,rate_JanDec2526,Dec_2025,rate_DecSep25,Sep_2025,rate_SepJul25,Jul_2025,rate_JulApr25,Apr_2025,rate_AprFeb25,Feb_2025
0,TH Nürnberg Georg Simon Ohm,Bayern,5383,74.82,71.0,2.23,22.0,0.00,22.0,0.16,19.0,0.00,19.0
1,HHU Düsseldorf,Nordrhein-Westfalen,1355,0.06,1279.0,0.23,1043.0,0.11,938.0,0.21,776.0,0.14,682.0
2,TH Köln,Nordrhein-Westfalen,786,0.02,769.0,0.18,651.0,0.09,596.0,0.13,529.0,0.18,450.0
3,Hochschule Meißen (FH) und Fortbildungszentrum,Sachsen,664,0.00,664.0,0.00,665.0,0.00,664.0,0.01,658.0,0.17,562.0
4,Universität Wuppertal,Nordrhein-Westfalen,568,1.90,196.0,0.30,151.0,0.51,100.0,0.45,69.0,0.15,60.0

In [15]:
# import new table

new_path_M = 'C:/Users/ywa/Documents/Data/UserReport/Jan_2026_Moodle/hei_data_total.xlsx'

new_df_M = pd.read_excel(new_path_M, usecols = ['count', 'provider'])

new_df_M.head()

                      provider  count
0  TH Nürnberg Georg Simon Ohm   5383
1                         DHBW   2084
2     FernUniversität in Hagen   1727
3               HHU Düsseldorf   1355
4                      TH Köln    786

In [16]:
# merge new table and existing table --> sanity check
print(len(new_df_M))
print(len(existing_df_M))

new_provider = new_df_M[~new_df_M['provider'].isin(existing_df_M['provider'])]

new_provider

506
506

Empty DataFrame
Columns: [provider, count]
Index: []

In [22]:
# merge the two table

merged_moodle = new_df_M.merge(existing_df_M, how = 'left', validate = 'one_to_one')

# switch column positions
print(len(merged_moodle.columns))

#merged_moodle = merged_moodle.iloc[:, [0, 2, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]]

merged_moodle.head()

14

,provider,state,count,Jan_2026,rate_JanDec2526,Dec_2025,rate_DecSep25,Sep_2025,rate_SepJul25,Jul_2025,rate_JulApr25,Apr_2025,rate_AprFeb25,Feb_2025
0,TH Nürnberg Georg Simon Ohm,Bayern,5383,5383,74.82,71.0,2.23,22.0,0.00,22.0,0.16,19.0,0.00,19.0
1,DHBW,Baden-Württemberg,2084,556,0.02,543.0,0.08,505.0,0.05,479.0,0.46,327.0,0.14,286.0
2,FernUniversität in Hagen,Nordrhein-Westfalen,1727,295,0.03,287.0,0.12,257.0,0.16,221.0,0.15,192.0,0.08,177.0
3,HHU Düsseldorf,Nordrhein-Westfalen,1355,1355,0.06,1279.0,0.23,1043.0,0.11,938.0,0.21,776.0,0.14,682.0
4,TH Köln,Nordrhein-Westfalen,786,786,0.02,769.0,0.18,651.0,0.09,596.0,0.13,529.0,0.18,450.0

In [26]:
# rename new count column
merged_moodle.rename(columns = {'provider' : 'Hochschule', 'state' : 'Bundesland',  'count' : 'Jan_2026_Total'}, inplace = True)

merged_moodle.head()

,provider,state,Jan_2026_Total,Jan_2026,rate_JanDec2526,Dec_2025,rate_DecSep25,Sep_2025,rate_SepJul25,Jul_2025,rate_JulApr25,Apr_2025,rate_AprFeb25,Feb_2025
0,TH Nürnberg Georg Simon Ohm,Bayern,5383,5383,74.82,71.0,2.23,22.0,0.00,22.0,0.16,19.0,0.00,19.0
1,DHBW,Baden-Württemberg,2084,556,0.02,543.0,0.08,505.0,0.05,479.0,0.46,327.0,0.14,286.0
2,FernUniversität in Hagen,Nordrhein-Westfalen,1727,295,0.03,287.0,0.12,257.0,0.16,221.0,0.15,192.0,0.08,177.0
3,HHU Düsseldorf,Nordrhein-Westfalen,1355,1355,0.06,1279.0,0.23,1043.0,0.11,938.0,0.21,776.0,0.14,682.0
4,TH Köln,Nordrhein-Westfalen,786,786,0.02,769.0,0.18,651.0,0.09,596.0,0.13,529.0,0.18,450.0

In [25]:
# calculate rates??

,provider,state,count,Jan_2026,rate_JanDec2526,Dec_2025,rate_DecSep25,Sep_2025,rate_SepJul25,Jul_2025,rate_JulApr25,Apr_2025,rate_AprFeb25,Feb_2025
0,TH Nürnberg Georg Simon Ohm,Bayern,5383,5383,74.82,71.0,2.23,22.0,0.00,22.0,0.16,19.0,0.00,19.0
1,DHBW,Baden-Württemberg,2084,556,0.02,543.0,0.08,505.0,0.05,479.0,0.46,327.0,0.14,286.0
2,FernUniversität in Hagen,Nordrhein-Westfalen,1727,295,0.03,287.0,0.12,257.0,0.16,221.0,0.15,192.0,0.08,177.0
3,HHU Düsseldorf,Nordrhein-Westfalen,1355,1355,0.06,1279.0,0.23,1043.0,0.11,938.0,0.21,776.0,0.14,682.0
4,TH Köln,Nordrhein-Westfalen,786,786,0.02,769.0,0.18,651.0,0.09,596.0,0.13,529.0,0.18,450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,Yildiz Technical University,Not in Germany,1,1,0.00,1.0,0.00,1.0,0.00,1.0,0.00,1.0,0.00,1.0
502,Academia de Studii Economice din Bucuresti,Not in Germany,1,1,0.00,1.0,0.00,1.0,0.00,1.0,0.00,1.0,0.00,1.0
503,Abdelhamid Mehri University of Constantine,Not in Germany,1,1,0.00,1.0,0.00,1.0,0.00,1.0,0.00,1.0,inf,0.0
504,Université Sidi Mohammed Ben Abdellah,Not in Germany,1,1,0.00,1.0,0.00,1.0,0.00,1.0,0.00,1.0,0.00,1.0
505,Swinburne University of Technology,Not in Germany,1,1,0.00,1.0,0.00,1.0,0.00,1.0,0.00,1.0,0.00,1.0

In [52]:
# import january 26

path_janM_total = 'C:/Users/ywa/Documents/Data/UserReport/Jan_2026_Moodle/hei_data_total.xlsx'

jan26_total_M = pd.read_excel(path_janM_total)

path_janM = 'C:/Users/ywa/Documents/Data/UserReport/Jan_2026_Moodle/hei_data_moodle.xlsx'

jan26_M = pd.read_excel(path_janM)


# import december 25
path_decM = 'C:/Users/ywa/Documents/Data/UserReport/Dec_2025_Moodle/hei_data_moodle.xlsx'

dec25_M = pd.read_excel(path_decM, usecols = ['count', 'provider'])

# merge jan26 and dec25

merged_moodle = jan26_M.merge(dec25_M, how = 'left', on = 'provider', validate = 'one_to_one')

merged_moodle.columns = ['provider', 'Jan_2026', 'state', 'Dec_2025']

# import september 25

path_sepM = 'C:/Users/ywa/Documents/Data/UserReport/Sep_2025_Moodle/hei_data_moodle.xlsx'

sep_25_M = pd.read_excel(path_sepM, usecols = ['count', 'provider'])

merged_moodle = merged_moodle.merge(sep_25_M, how = 'left', on = 'provider', validate = 'one_to_one')

merged_moodle.columns = ['provider', 'Jan_2026', 'state', 'Dec_2025', 'Sep_2025']

merged_moodle.head()

# import july 25

path_julM = 'C:/Users/ywa/Documents/Data/UserReport/Jul_2025_Moodle/hei_data_moodle.xlsx'

jul_25_M = pd.read_excel(path_julM, usecols = ['count', 'provider'])

merged_moodle = merged_moodle.merge(jul_25_M, how = 'left', on = 'provider', validate = 'one_to_one')

merged_moodle.columns = ['provider', 'Jan_2026', 'state', 'Dec_2025', 'Sep_2025', 'Jul_2025']

merged_moodle.head()

# import april 25

path_aprM = 'C:/Users/ywa/Documents/Data/UserReport/Apr_2025_Moodle/hei_data_moodle.xlsx'

apr_25_M = pd.read_excel(path_aprM, usecols = ['count', 'provider'])

merged_moodle = merged_moodle.merge(apr_25_M, how = 'left', on = 'provider', validate = 'one_to_one')

merged_moodle.columns = ['provider', 'Jan_2026', 'state', 'Dec_2025', 'Sep_2025', 'Jul_2025', 'Apr_2025']

# import feburary 25

path_febM = 'C:/Users/ywa/Documents/Data/UserReport/Feb_2025_Moodle/hei_data_moodle.xlsx'

feb_25_M = pd.read_excel(path_febM, usecols = ['count', 'provider'])

merged_moodle = merged_moodle.merge(feb_25_M, how = 'left', on = 'provider', validate = 'one_to_one')

merged_moodle.columns = ['provider', 'Jan_2026', 'state', 'Dec_2025', 'Sep_2025', 'Jul_2025', 'Apr_2025', 'Feb_2025']

# reordering columns

#merged_moodle = merged_moodle.iloc[:, [0, 2, 1, 3, 4, 5, 6, 7]]

merged_moodle.head()

,provider,state,Jan_2026,Dec_2025,Sep_2025,Jul_2025,Apr_2025,Feb_2025
0,TH Nürnberg Georg Simon Ohm,Bayern,5383,71.0,22.0,22.0,19.0,19.0
1,HHU Düsseldorf,Nordrhein-Westfalen,1355,1279.0,1043.0,938.0,776.0,682.0
2,TH Köln,Nordrhein-Westfalen,786,769.0,651.0,596.0,529.0,450.0
3,Hochschule Meißen (FH) und Fortbildungszentrum,Sachsen,664,664.0,665.0,664.0,658.0,562.0
4,Universität Wuppertal,Nordrhein-Westfalen,568,196.0,151.0,100.0,69.0,60.0

In [54]:
# deal with missing values (due to merge)
merged_moodle.fillna(0, inplace = True)

In [56]:
merged_moodle['rate_JanDec2526'] = uni_growth(merged_moodle['Jan_2026'], merged_moodle['Dec_2025'])
merged_moodle['rate_DecSep25'] = uni_growth(merged_moodle['Dec_2025'], merged_moodle['Sep_2025'])
merged_moodle['rate_SepJul25'] = uni_growth(merged_moodle['Sep_2025'], merged_moodle['Jul_2025'])
merged_moodle['rate_JulApr25'] = uni_growth(merged_moodle['Jul_2025'], merged_moodle['Apr_2025'])
merged_moodle['rate_AprFeb25'] = uni_growth(merged_moodle['Apr_2025'], merged_moodle['Feb_2025'])


# reordering columns
merged_moodle = merged_moodle.iloc[:, [0, 1, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12, 7]]

merged_moodle.head()

,provider,state,Jan_2026,rate_JanDec2526,Dec_2025,rate_DecSep25,Sep_2025,rate_SepJul25,Jul_2025,rate_JulApr25,Apr_2025,rate_AprFeb25,Feb_2025
0,TH Nürnberg Georg Simon Ohm,Bayern,5383,74.82,71.0,2.23,22.0,0.00,22.0,0.16,19.0,0.00,19.0
1,HHU Düsseldorf,Nordrhein-Westfalen,1355,0.06,1279.0,0.23,1043.0,0.11,938.0,0.21,776.0,0.14,682.0
2,TH Köln,Nordrhein-Westfalen,786,0.02,769.0,0.18,651.0,0.09,596.0,0.13,529.0,0.18,450.0
3,Hochschule Meißen (FH) und Fortbildungszentrum,Sachsen,664,0.00,664.0,0.00,665.0,0.00,664.0,0.01,658.0,0.17,562.0
4,Universität Wuppertal,Nordrhein-Westfalen,568,1.90,196.0,0.30,151.0,0.51,100.0,0.45,69.0,0.15,60.0

In [27]:
# export excel to to drive
#merged_moodle.to_excel('C:/Users/ywa/Documents/Data/UserReport/HEI_semester_growth_M.xlsx', index = False)